language: node_js
node_js:
- node
before_deploy:
    - git checkout master
    - npm run prerelease
    - npm version minor --force -m "Build %s [skip ci]"
deploy:
  provider: npm
  email: brady.holt@gmail.com
  api_key:
    secure: "u0uH+vog8NOcYkVj5yRl0zzCbRUkiD2UZ1Ta3i9w2BlVaeiOzuIi5BQZqCvD1ahSQ1OJ99GDpaq01OQwahso2+wLT9Jx2WzOY+hSQSquNToXeBObG0meyPMNinLPJ8cW/vaqoXw0Jdmp/AzIhw12XQ91PwBoGu0hRXywLyMqHT6A3k0+iYh8Xd5iCJTu9iwE0EAfPGQLfHPcQyu+O+jcDDcN/H+ZjvqtlyCYevg6ddBH9gWKeeiXKBDMFGqH1yh7bjwUR71R+pQItTv6IM9y58YTGWz8AzUxrsgb01mvclTRhEuk3wr3Smds8Qk7jmAGboGhKKIwe4pPaEmGKpD3o26evazNxmZczjvrjFS/Wq7izyw24Ad4TpZtry7emSWITNK280TbDteQE96VqkLtmjrb4oUc0Sy4J6joBPavbxtxD7PIa2mowfqNGuCVGb4SzREzrM16NxvV82j3FPRmksdnKSq184GgGOQRD57a7l6xMLwwWYKaG88oX7ki6icSFwEWN0BQ+B8sQM0y4wDkrnz/4qXwyfCeVwjV62jfMfmlpj4JvN7b46U8ne72pncWum8uucP2MlXK457gbUJTKFwhlQSjMyngwCHoK5YnTRuq/1g76CKaRqoNu2CQXDCEdm64QBcmc++IxF1JfbkVCLvrtlzhEagsM6TIy63YJNg="
  on:
    repo: bradymholt/cRonstrue
  skip_cleanup: true
after_deploy:
    - git config --global user.email "travis@travis-ci.org"
    - git config --global user.name "Travis CI"
    - git remote add gh-origin https://${GH_TOKEN}@github.com/${GH_REPO}.git
    - git push gh-origin master --tags
    - VERSION=$(node -p "require('./package.json').version")
    - |
      curl -H "Authorization: token ${GH_TOKEN}" -d '{"tag_name":"v'$VERSION'"}' https://api.github.com/repos/${GH_REPO}/releases
env:
  global:
    - GH_REPO=bradymholt/cRonstrue
    - secure: "KOgpxZSup8txtD1maRJNVjuveicCRAvEYzgw0bc7FDUQ/rCdsCsMqBNjET2j1dC2qbAsLhrWhlvCYW+TVnsTIwTfpXgD2V2cQpUAjbKPDabcUwk3lgn+eXCsIlY9Ts2F9TmwCCUCqwu5ddMHJTsDCjkUFN/7KQCg2evHzTQ2Xt9Mk0sc7PATmUh4l+MiWnWD2ESeclBnl6w/kSbmtaQIYWebtHm+Wo9FSwP1j6DekVPIR0Q8FLIP6/C7uKvEbKAM5VDTf3eE4q1HP6CSrUAyF42dnd9f1atzPrv1VIQNezQ8TJUVushE302pjjg0vNlCwOda7BlckWenX4xAr1/oGGDjyJDxD4b1NLenGzbP+kZzVpUdYfuuU15stLl3/JkRMObY/vC3NZop4xZ2fXeH6eDUlE/hfDdbcKs87jztb0Rw7JV/tZ4t9WhJXW/SHxrpzsUm9Fz1nPoE9XGdKSTE3/V+ssJel/EKLc2dLXbKBq8vbWvS6T6VLsNrjXuVkRiENJz3m8yTw8IvSoNau2UUH4jtMxCLp5XRDlj0KofewUIOqfu41ula0xm1thvW7gNcxpCqsNYrN4CIoQYqxx0cxOgRRYjCOzBu6tCDrhw1mzClZTDg2K9gewd3d9nbpZQOdhes9clQgPbQLSeBmLjUQPhFZV32sZ0RPyTqOAqikJI="
