language: node_js
node_js:
- node
before_deploy:
    - git checkout master
    - npm run prerelease
    - npm version minor --force -m "Build %s [skip ci]"
deploy:
  provider: npm
  email: brady.holt@gmail.com
  api_key:
    secure: vC97W5BjHJ5i3qu9m5sKltjmpr8quXL+4oxCU/Fk/1IxP26KDpJIn9p+QWa/qSwOqGdHfzbjVMhMULipKl/jjyTmz5RV2fmziY5gcA91rAY25glr4t90LvU9LCjMHU6lHIl0OydZrR91Bmrq8MzJthoTM7FXKKFTzPlu1EiS66rzmYB9mZvkGgoVX0jLyoWau/XP1kOr/mM5qFnQNil700e393KB9KD74vuB2lKHzQCLfBKX7pzr01MGTikw9ewrWm/aJtX6EvK9wD1glaGkzzSFXyb5cV3YCaxwqlaD/T3s4mfqIrJj4AJ90MQjOY1lKWYjdwc9jvWT5iAteB9IDZ6FYcS+jSIZpRectzMdGkBqhjmxomagAQ9RNgMwfDy+e98MU4Ye8BWh333vAmxkA4l8KmMpmSgAcU3wm5v5h91AdLGAkUKkgMa/FAQAu38lM8W03GAhdrT76D8KIUylyW4W9Lsk8V4+K86oY/OXbDkh0ZEAgHbgE/Gg9iQdtEbhrx6IykoFoO374z82r7/2iVO62dAUkgUa/VPeNQK7k+7pZER3i4qBTFqvkMgTGO1LFcG1q+bstUp8a+XpuQjMPHgWYFcyyynqDV5Twh/qCj9Cb3SFZAY/GikPmYemm6HP6jdKBCu3zUH9exl3hv7PHHEwd6sXeGbLpLG3Gj4nalA=
  on:
    repo: bradymholt/cRonstrue
  skip_cleanup: true
after_deploy:
    - git config --global user.email "travis@travis-ci.org"
    - git config --global user.name "Travis CI"
    - git remote add gh-origin https://${GH_TOKEN}@github.com/${GH_REPO}.git
    - git push gh-origin master --tags
    - VERSION=$(node -p "require('./package.json').version")
    - |
      curl -H "Authorization: token ${GH_TOKEN}" -d '{"tag_name":"v'$VERSION'"}' https://api.github.com/repos/${GH_REPO}/releases
env:
  global:
    - GH_REPO=bradymholt/cRonstrue
    - secure: "UkXHaD8vn3Jc7V5LckkdGjWKPf7ybOobcE+fO8NCpmUtxdU1//XjPogDfrh5xjO1NFW4Rx9ywoK7XURf+IfvkoZRLr5bFx9Rn/S4ca+BR3RHH4nuWx4MCZGp+y+jP55G4T+PRA3QfN1n0MPDJLdE2KRy+7H3MIH9bX6G/HXTZkkC53IXpuM+8NcE+/MRKqGovr0vIumz3p0sJIJFQdDnepVsVxPbiWn42zLgbUZjiZBDxzJ4d3z647i16917/VijI4vDbIRxPk4/6sS6DfEEhJMrUxMsof+T8IJTUzhyQMwe18Io3wy5HyBePHZiKArLpoGaXe2eJCSdgY9zevBBaXw3b/hTADYQfIqewdwBaxbIfZCAqkhi7VbWaHItg7JXgMZbIv9OFXmBqomzXod0a4TVPDdbDsjLq/LAwy5FAQmGsdMceacht/5gCjAeHxnrRHnNvgzhOMAMq45fAXEyZavd8u2SDEMPrYIHQ1otibs316J9ZbQXB2hR82LllptLFxSLyrFqodw8hvpvUf5w8peCzB6pciGpfof961De63Z0QDVGHfKuTNuc6GNy+41+of9Bro4lGMVFaaPo5PNyBn6HPnLUr0v/ZQSmB3qpRDOMw+slWXveCgTIkJ9k58W8i61IwoYqgS2iV03+WZYeEUpqHl98jjeesPEIxdkA4Uk="
